apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wordpress-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress-repo
  # filterTags:
  #   pattern: ""
  policy:
    semver:
      range: ">=6.0.0"
