apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: wordpress
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress
  policy:
    semVer:
      range: "6.x.x"
