apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "6.4.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    mariadb:
      auth:
        rootPassword: "adminPass123"
        database: "wordpress"
    wordpressUsername: "admin"
    wordpressPassword: "password123"
    wordpressEmail: "user@example.com"
    service:
      type: ClusterIP
