apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "20.1.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    image:
      repository: bitnami/wordpress
      tag: 6.5.0 # {"$imagepolicy": "flux-system:wordpress-policy:tag"}
    mariadb:
      auth:
        rootPassword: "adminPass123"
        database: "wordpress"
    wordpressUsername: "admin"
    wordpressPassword: "password123"
    wordpressEmail: "user@example.com"
    service:
      type: ClusterIP
