apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 10m
  path: "../../apps/dev/wordpress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-apps-repo
  targetNamespace: default
