apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 10m
  path: "../../apps/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
