apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
spec:
  values:
    replicaCount: 3
    mariadb:
      primary:
        persistence:
          size: "10Gi"
    service:
      type: LoadBalancer
